### ISSUE TITLE
Amalgam without require?

### ISSUE THREAD

**Issue by allquixotic** [Stepets/utf8.lua#10]
Hello,

I am trying to use this library in a Lua "sandbox" environment (within an application), where I have:

- Lua 5.1 based interpreter,
- No `require`,
- No access to the native platform, so no `ffi`, no `os`, etc.
- No external dependencies, unless I can also bring them in as pure Lua code and they work with 5.1 without any native platform or `require` access.

Multiple files are handled by a well-defined load order configured within the application, but I would also prefer to bring in everything "statically" into a single file.

What is the minimum set of .lua files from this project that I would need to make a working version of utf8.lua without any external dependencies? Should I include the modifiers or do they all have external dependencies?

My goal is to define a global `utf8` table that contains all of the functionality of this library in a single file. I would prefer if it supports lazy init, because sometimes this code might be "loaded" but not actually executed, and if the initialization takes time, I would rather skip that init time when the utf8 code isn't needed.

I was able to use `squish` (a tool written in Lua that combines multiple Lua files into one) to generate an amalgamated file, but it still depends on `require` to do what you would expect because of `utf8:require` all throughout the code. `squish` is not smart enough to translate "through" the dynamic `require` wrapper in utf8; if they were static `require`s it would be able to follow them and amalgamate the code intelligently.

I _was_ able to get all of the code to _load_ (uninitialized) in my environment, so I know that the Lua interpreter in my environment was able to syntactically validate all of the amalgamated code from `squish`; but the problem was that as soon as it hits `utf8:require`'s native `require` call-through, it dies because `require` is `nil` in this environment.

Any ideas how best to address this?

**Comment by Stepets** [comment]
Hello, it seems like to do statically linking the library one should place modules into a table and `utf8.require` function should be changed to lookup in that table.

Resulting file migth look like this:
```Lua
local static_modules = {}

static_modules["util"] = -- <contents of "util.lua" with leading "return" keyword being cut-off>
static_modules["primitives.init"] = --<contents of "primitives/init.lua" with leading "return" keyword being cut-off>
-- etc, modules can be added in any order

-- contents of init.lua

local loaded = {}
function utf8:require(module_name)
  if loaded[module_name] then
    return loaded[module_name]
  end

  local mod = static_modules[module_name]
  if type(mod) == 'function' then
    mod = mod(self)
    loaded[module_name] = mod
  end
  return mod
end
```

**Comment by Stepets** [comment]
Closing issue as it seems to be solved. Feel free to reopen it.
