### ISSUE TITLE
lower() and upper() support for utf8data.lua

### ISSUE THREAD

**Issue by tatewise** [Stepets/utf8.lua#13]
This is related to the closed issue [lower() and upper() do not work on UTF-8 strings (Lua 5.1, Lua5.3)](https://github.com/Stepets/utf8.lua/issues/7)

In [utf8.lua/README.md](https://github.com/Stepets/utf8.lua/blob/master/README.md) under **Usage** it says: "This library can be used as drop-in replacement for vanilla string library."

In [utf8.lua/primitives/dummy.lua](https://github.com/Stepets/utf8.lua/blob/master/primitives/dummy.lua) it says:
```
-- If utf8data.lua (containing the lower<->upper case mappings) is loaded, these
-- additional functions are available:
-- * utf8upper(s)
-- * utf8lower(s)
```
**utf8data.lua** mapping tables can be obtained from [github.com/artemshein/luv](https://github.com/artemshein/luv/blob/master/utf8data.lua) and elsewhere.

There appear to be no utf8 drop-in replacements for **string.upper** or **string.lower** functions.
Even if **require("utf8data")** is used with a copy of **utf8data.lua** then no additional functions are available.

Earlier versions of the utf8 library had script such as below that seems to offer the above functions but now appears to be missing.
See [Id: utf8.lua 147 2007-01-04 00:57:00Z pasta](https://github.com/vhallac/ouf_grid/blob/master/lib/UTF8/utf8.lua) lines 244 - 293
Is it possible to incorporate those functions back into the utf8 library please?
```
-- replace UTF-8 characters based on a mapping table
local function utf8replace (s, mapping)
	-- argument checking
	if type(s) ~= "string" then
		error("bad argument #1 to 'utf8replace' (string expected, got ".. type(s).. ")")
	end
	if type(mapping) ~= "table" then
		error("bad argument #2 to 'utf8replace' (table expected, got ".. type(mapping).. ")")
	end

	local pos = 1
	local bytes = s:len()
	local charbytes
	local newstr = ""

	while pos <= bytes do
		charbytes = utf8charbytes(s, pos)
		local c = s:sub(pos, pos + charbytes - 1)

		newstr = newstr .. (mapping[c] or c)

		pos = pos + charbytes
	end

	return newstr
end

-- identical to string.upper except it knows about unicode simple case conversions
local function utf8upper (s)
	return utf8replace(s, utf8_lc_uc)
end

-- install in the string library
if not string.utf8upper and utf8_lc_uc then
	string.utf8upper = utf8upper
end

-- identical to string.lower except it knows about unicode simple case conversions
local function utf8lower (s)
	return utf8replace(s, utf8_uc_lc)
end

-- install in the string library
if not string.utf8lower and utf8_uc_lc then
	string.utf8lower = utf8lower
end
```
BTW:
The utf8replace function seems over complex and its body could use the utf8.charpattern as below:
```
	local newstr = s:gsub( "([\1-\x7F\xC2-\xF4][\x80-\xBF]*)", mapping )
```

**Comment by tst2005** [comment]
quick idea:
The "utf8data" is not small, if you add it, please keep it as a separate file.
It helps me generate an all-in-one module with or without it.

**Comment by Stepets** [comment]
Implemented it in https://github.com/Stepets/utf8.lua/tree/13_lower_upper_utf8data, also updated readme
Unfortunately now I cannot test if it works

**Comment by tatewise** [comment]
Agreed. Although it is only 33KB and could be pruned down to remove unnecessary mappings.
The idea is that a **require("utf8data")** statement must optionally be used before the **require("utf8")** statement.

I have modified my copy of [utf8.lua/primitives/dummy.lua](https://github.com/Stepets/utf8.lua/blob/master/primitives/dummy.lua) to include the script below at about line 152 and it behaves perfectly.
```
-- replace UTF-8 characters based on a mapping table
local function utf8replace (s, mapping)
  -- argument checking
  if type(s) ~= "string" then
    error("bad argument #1 to 'utf8replace' (string expected, got ".. type(s).. ")")
  end
  if type(mapping) ~= "table" then
    error("bad argument #2 to 'utf8replace' (table expected, got ".. type(mapping).. ")")
  end

  -- uses utf8.charpattern but without control chars
  local newstr = s:gsub( "([\20-\x7F\xC2-\xF4][\x80-\xBF]*)", mapping )

  return newstr
end

-- identical to string.upper except it knows about unicode simple case conversions
local function utf8upper (s)
  return utf8replace(s, utf8_lc_uc)
end

-- install in the library
if utf8_lc_uc then
  upper = utf8upper
end

-- identical to string.lower except it knows about unicode simple case conversions
local function utf8lower (s)
  return utf8replace(s, utf8_uc_lc)
end

-- install in the library
if utf8_uc_lc then
  lower = utf8lower
end
```

**Comment by tatewise** [comment]
Thank you Stepets. I will check that version but it looks good.

**Comment by Stepets** [comment]
Fixed config lookup, now it should work

**Comment by tatewise** [comment]
Thank you Stepan, it may take a while to fully test because I rely on somebody else to package the library with a product release.
I will confirm if it works correctly after our package update.

**Comment by tatewise** [comment]
One small problem I have spotted is that the utf8.upper and utf8.lower now return two values whereas previous versions did not and string.upper and string.lower do not.
The extra value is the number of character substitutions performed by utf8.raw.gsub( s, utf8charpattern, mapping ) in utf8replace
That side effect could disrupt existing scripts so it would be better to have:
```
  s = utf8.raw.gsub( s, utf8charpattern, mapping )
  return s
```
or
```
  return ( utf8.raw.gsub( s, utf8charpattern, mapping ) )
```

**Comment by Stepets** [comment]
Thanks for feedback! Fixed this issue with extra return value.
When I will be home next week I will add test cases and will merge it into master.

**Comment by tatewise** [comment]
Thank you for your rapid support.
I have been able to perform some more testing and found a problem, not just with new version 179, but also master version 147.
I could have started a new issue but decided it was tightly bound with this ongoing issue.

In Lua 5.3 there is a built-in **utf8.charpattern = "[\0-\x7F\xC2-\xF4][\x80-\xBF]*"**

Every utf8 library version sets **utf8.charpattern = "[\0-\x7F\xC2-\xF4][\x80-\xBF]*"**

In Lua 5.1 **\0** is invalid and **%z** must be used so every utf8 library version fails when **utf8.charpattern** is used.
There is the [compat53](https://github.com/keplerproject/lua-compat-5.3) library that sets **utf8.charpattern = "[%z\1-\x7F\xC2-\xF4][\x80-\xBF]*"** and works OK.
When any utf8 library **utf8:init()** is invoked it sets **utf8.charpattern = "[\0-\x7F\xC2-\xF4][\x80-\xBF]*"** that fails when used.

So the utf8 library should preserve **utf8.charpattern** if it exists or set it to **"[%z\1-\x7F\xC2-\xF4][\x80-\xBF]*"**
e.g.
**utf8.charpattern = utf8.charpattern or "[%z\1-\x7F\xC2-\xF4][\x80-\xBF]*"**
In Lua 5.3 or later or when compat53 is applied that will retain the existing value.
In Lua 5.2 or earlier without compat53 it will set **"[%z\1-\x7F\xC2-\xF4][\x80-\xBF]*"**

**Comment by tatewise** [comment]
FYI: This what I found worked.
Modify the start of utf8/init.lua to set up charpattern:
```
local module_path = ...
module_path = module_path:match("^(.-)init$") or (module_path .. '.')

local ffi_enabled, ffi = pcall(require, 'ffi')

local pattern = "[%z\1-\127\194-\244][\128-\191]*"
if utf8 then
  pattern = utf8.charpattern or pattern
end

local utf8 = {
  charpattern = pattern,
  config = {},
```
and in utf8/primitives/dummy.lua modify line 74 to:
```
local utf8charpattern = utf8.charpattern or '[\0-\127\194-\244][\128-\191]*'
```

**Comment by Stepets** [comment]
`"[%z\1-\127\194-\244][\128-\191]*"` should work in both cases (`\0` supported or not, hex-codes supported or not). So I made it default in acf4a19.

**Comment by tatewise** [comment]
Thank you. Yes, that works fine as `%z` although deprecated is still supported in Lua 5.3 and even Lua 5.4 too.
So that all looks good to go and become the master except for a minor correction to README.md under Configuration: for lower and upper functions where it says to use `local utf8 = require(".utf8")` which should be `utf8 = require(".utf8")` otherwise I found it does not work correctly.

Please let me know when the master has been updated.

**Comment by tatewise** [comment]
The issues with lower() and upper() support were fixed extremely quickly. Thank you.
What are your current plans to merge this fork into the master?

**Comment by Stepets** [comment]
Hello, merged it
