### ISSUE TITLE
Help a Lua novice?

### ISSUE THREAD

**Issue by imfatant** [Stepets/utf8.lua#14]
Hi,

I'm a Lua novice. I'm using Lua 5.4.3.

In my project folder I used `git clone https://github.com/Stepets/utf8.lua`. This created a subfolder called `utf8.lua`.

Near the beginning of my Lua code, I have `local utf8 = require('.utf8'):init()`. When I try to execute the code I get:

```
~/src/test$ ./new.lua
/usr/local/bin/lua: ./new.lua:5: module '.utf8' not found:
        no field package.preload['.utf8']
        no file '/usr/local/share/lua/5.4//utf8.lua'
        no file '/usr/local/share/lua/5.4//utf8/init.lua'
        no file '/usr/local/lib/lua/5.4//utf8.lua'
        no file '/usr/local/lib/lua/5.4//utf8/init.lua'
        no file './/utf8.lua'
        no file './/utf8/init.lua'
        no file '/usr/local/lib/lua/5.4//utf8.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './/utf8.so'
        no file '/usr/local/lib/lua/5.4/.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './.so'
stack traceback:
        [C]: in function 'require'
        ./new.lua:5: in main chunk
        [C]: in ?
```

I suspect I need to configure `package.path`, but I'm not sure how. Can you help?

**Comment by Stepets** [comment]
Hello, you should rename folder from `utf8.lua` to `utf8` for `require('.utf8')` to work.

**Comment by Stepets** [comment]
Updated installation section in readme, thanks!
