### ISSUE TITLE
basic test cases

### ISSUE THREAD

**Issue by bitinn** [Stepets/utf8.lua#2]
I have been using this library recently since I don't need the performance of C modules and much prefer the simplicity. 

I imagine adapting existing test cases won't be too difficult ([some have the same API](https://github.com/starwing/luautf8)), if you don't have time, I might consider working on it :)

**Comment by Stepets** [comment]
Hello, I'm really happy to hear this library is being used!
I ran those tests and there are some failing tricky tests.
But unfortunately, now I don't have time to work on it.

**Comment by bitinn** [comment]
Oh good to know, still, it would be nice to know what edge cases are failing, so people don't stumble into them. When you say `those tests`, you are referring to the repo I linked right?

**Comment by Stepets** [comment]
Right.
tests from test_compat.lua

``` Lua
assert(utf8.find("", "") == 1) -- gives "nil" instead "1, 0"
assert(utf8.find("", "", 1) == 1) -- same

assert(utf8.byte("\xe4") > 127) -- 120 
assert(utf8.sub("\000123456789",3,5) == "234") -- \000 is "Invalid UTF-8 character"
assert(utf8.sub("\000123456789", 8) == "789") -- same

assert(utf8.byte("hi", 9, 10) == nil) -- fails with "comparing nil with number"
assert(utf8.char() == "") -- same
assert(utf8.byte("\n\n", 2, -1) == 10) -- returns nil
```

I assume bugs related to symbol parsing are simple to fix (>= 0, ~= nil, etc).

To fix find("", "") you should look at matcher first and last functions in function list.
Matcher designed as list of chars, and list of checker-functions, checker-functions can mark positions on lists to rollback to. It's like state machine.

Hope it helps, may the force be with you :)

**Comment by bitinn** [comment]
`match(input, '([^%s]+)%s%s')` should match the last 2 space but I find it able to match just one. `string.match` doesn't seem to behave this way, not sure it's a bug related to your comment or not.

(eg. `match('abc abc', '([^%s]+)%s%s')` will give `abc`)

**Comment by Stepets** [comment]
It took me some time to fix this
