### ISSUE TITLE
Incorrect matching case

### ISSUE THREAD

**Issue by shmuz** [Stepets/utf8.lua#3]
The following example gives different results between string and utf8.lua libraries:
```lua
local u = (require 'stepets.utf8'):init()

local subj = "items"
local patt = "^(.-)([^.]*)$"

print(      u.match(subj, patt) ) --> nil
print( string.match(subj, patt) ) -->         items
```

**Comment by Stepets** [comment]
Thank you for reporting this!
Seems like I completely forgot to test $ anchor processing.

It's fixed now
https://github.com/Stepets/utf8.lua/blob/06b1457ac5975a18628c3771804a3e3c216ecfca/test/test.lua#L178-L182
