### ISSUE TITLE
Another incorrect matching case

### ISSUE THREAD

**Issue by shmuz** [Stepets/utf8.lua#4]
```Lua
local u = (require "stepets.utf8"):init()

local subj = "ab.?"
local patt = "%?"
local repl = "123"

print(      u.gsub(subj, patt, repl) ) --> 123a123b123.123?123     5
print( string.gsub(subj, patt, repl) ) --> ab.123  1
```

**Comment by Stepets** [comment]
Thanks again!

Fixed
https://github.com/Stepets/utf8.lua/blob/681e935f244b2d3fe6ad9b5103a1059c9e038749/test/test.lua#L184-L185
https://github.com/Stepets/utf8.lua/blob/681e935f244b2d3fe6ad9b5103a1059c9e038749/test/charclass_compiletime.lua#L113-L116

P.S. Do you mind sharing your regex archive? :)

**Comment by shmuz** [comment]
> Do you mind sharing your regex archive? :)

I don't have a separate "regex archive". I have Far Manager application (you probably heard about it) and a bunch of various Lua plugins and macros installed (most of them use pattern matching).

Then I take your library and replace Far Manager's built-in library with it.
Then the things stop work and I investigate why.
