### ISSUE TITLE
Yet another incorrect matching case

### ISSUE THREAD

**Issue by shmuz** [Stepets/utf8.lua#5]
```Lua
local u = (require "stepets.utf8"):init()

local subj = "ab"
local patt = "a"
local repl = "%1"

print( string.gsub(subj, patt, repl) ) --> ab      1
print(      u.gsub(subj, patt, repl) )
   --> attempt to concatenate field '?' (a nil value)
```

**Comment by shmuz** [comment]
`%1` is legal (and should work the same as `%0`) when no capture is specified.

But if we specify say `%5` then the errors differ between string and utf8.lua libraries.
- string library says "invalid capture index" which is very clear
- utf8.lua says "attempt to concatenate field '?' (a nil value)".

**Comment by Stepets** [comment]
Thanks again!
Didn't find about this in docs, but surely lua strings library behaves this way.

Fixed
https://github.com/Stepets/utf8.lua/blob/59a5228b1b7e8001aada73f1032363e567f4aaf3/test/test.lua#L187-L190
