### ISSUE TITLE
Error in Lua 5.3 with pattern longger than 1

### ISSUE THREAD

**Issue by robertlzj** [Stepets/utf8.lua#9]
Example not work in Lua 5.3. 
Seems any pattern length greater than 1 cause error.
Test Lua 5.1 is fine.
Coded in UTF8.
```lua
local utf8 = require('.utf8'):init()
print(utf8.find('abc',"a"))--ok
print(utf8.find('abc',"ab"))--crash
```
Error message like:
`C:\ProgramFiles\ZeroBraneStudio\bin\lua53.exe: ...gramFiles\ZeroBraneStudio\lualibs/\utf8\regex_parser.lua:77: [string "12"]:24: unexpected symbol near '.0'
stack traceback:
	[C]: in function 'assert'
	...gramFiles\ZeroBraneStudio\lualibs/\utf8\regex_parser.lua:77: in function '.utf8.regex_parser'
	...mFiles\ZeroBraneStudio\lualibs/\utf8\functions\lua53.lua:16: in function 'get_matcher_function'
	...mFiles\ZeroBraneStudio\lualibs/\utf8\functions\lua53.lua:24: in function '.utf8.functions.lua53.find'
	...sers\RobertLin\Documents\Lua\LuaAgain2015\PathSearch.lua:16: in main chunk
	[C]: in ?`

**Comment by Stepets** [comment]
Sorry, cannot reproduce this error. I downloaded the ZBS version 1.90 and ran this example script with all provided Lua interpreters (5.0, 5.2, 5.3) output is the following:
```
Program starting as '"C:\Users\Stepa\Downloads\ZeroBraneStudio\bin\lua53.exe" -e "io.stdout:setvbuf('no')" "C:\Users\Stepa\test.lua"'.
Program 'lua53.exe' started in 'C:\Users\Stepa' (pid: 1476).
1	1
1	2
Program completed in 0.04 seconds (pid: 1476).
```

My guess is you might be using outdated code version.

**Comment by Stepets** [comment]
Can you show program output with such configuration?
```
local utf8 = require('.utf8')
utf8.config = {
  debug = utf8:require("util").debug
}
utf8:init()
print(utf8.find('abc',"a"))--ok
print(utf8.find('abc',"ab"))--crash
```

**Comment by Stepets** [comment]
Feel free to reopen the issue if this behaviour can be reproduced and you have a debug output.
